//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROPERTY_MANAGER.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROPERTY_MANAGER.Domain.Exceptions.MessagesExceptions", typeof(MessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner&apos;s age cannot exceed 100 years..
        /// </summary>
        internal static string AgeCannotExceed100 {
            get {
                return ResourceManager.GetString("AgeCannotExceed100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner must be at least 18 years old..
        /// </summary>
        internal static string AgeMustBeAtLeast18 {
            get {
                return ResourceManager.GetString("AgeMustBeAtLeast18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birthday cannot be a future date..
        /// </summary>
        internal static string BirthdayCannotBeInFuture {
            get {
                return ResourceManager.GetString("BirthdayCannotBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sale date cannot be in the future..
        /// </summary>
        internal static string DateSaleCannotBeInFuture {
            get {
                return ResourceManager.GetString("DateSaleCannotBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path or URL cannot be empty..
        /// </summary>
        internal static string FileCannotBeEmpty {
            get {
                return ResourceManager.GetString("FileCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must be a .jpg, .jpeg, or .png file..
        /// </summary>
        internal static string FileTypeNotValid {
            get {
                return ResourceManager.GetString("FileTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ID proporcionado no es válido..
        /// </summary>
        internal static string GuidNotValid {
            get {
                return ResourceManager.GetString("GuidNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo URL cannot be empty..
        /// </summary>
        internal static string PhotoCannotBeEmpty {
            get {
                return ResourceManager.GetString("PhotoCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo must be a .jpg, .jpeg, or .png file..
        /// </summary>
        internal static string PhotoFileTypeNotValid {
            get {
                return ResourceManager.GetString("PhotoFileTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo URL is not valid..
        /// </summary>
        internal static string PhotoUrlNotValid {
            get {
                return ResourceManager.GetString("PhotoUrlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price must be greater than zero..
        /// </summary>
        internal static string PriceNotValid {
            get {
                return ResourceManager.GetString("PriceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must have at least 6 characters.
        /// </summary>
        internal static string SizeFieldAddressNotValid {
            get {
                return ResourceManager.GetString("SizeFieldAddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must have at least 4 characters.
        /// </summary>
        internal static string SizeFieldCodeInternalNotValid {
            get {
                return ResourceManager.GetString("SizeFieldCodeInternalNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must have at least 3 characters.
        /// </summary>
        internal static string SizeFieldNameNotValid {
            get {
                return ResourceManager.GetString("SizeFieldNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tax cannot be a negative value..
        /// </summary>
        internal static string TaxCannotBeNegative {
            get {
                return ResourceManager.GetString("TaxCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tax cannot exceed 100%..
        /// </summary>
        internal static string TaxCannotExceed100Percent {
            get {
                return ResourceManager.GetString("TaxCannotExceed100Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property value must be a positive number..
        /// </summary>
        internal static string ValueMustBePositive {
            get {
                return ResourceManager.GetString("ValueMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property value cannot be lower than $1,000..
        /// </summary>
        internal static string ValueTooLow {
            get {
                return ResourceManager.GetString("ValueTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year of property must be greater than 1900.
        /// </summary>
        internal static string YearNotValid {
            get {
                return ResourceManager.GetString("YearNotValid", resourceCulture);
            }
        }
    }
}
